### PR TITLE
Prepare init phase

### PR DESCRIPTION
**Pull request by Entouanes**
# What's new
- Extended the timeline component to be able to display the prepare+init phases of an action if they exist
- Added a toolbar menu to select which phase to display (at least one phase is displayed)

### CODE REVIEW

**Comment by zzeekk** [comment]
Nice!
My two cents on @pgruetter's points:
1) In my opinion the duration should be the sum of all intervals displayed, e.g. if Prep/Init/Exec is displayed it should be durationPrep + durationInit + duration Exec. If we would just display tstmpExecEnd - tstampPrepStart the value would be unusable as well...
2) i disagree, normally i'm only interested in exec phase. Showing all phases for large pipelines looks also quite complex and can be confusing.

**Comment by pgruetter** [comment]
> 2. i disagree, normally i'm only interested in exec phase. Showing all phases for large pipelines looks also quite complex and can be confusing.

I see your point, especially for larger pipelines. Let's keep this default then.

**Comment by Entouanes** [comment]
> 3. A strange effect I noticed: When I select all 3 Phases, it correctly displays all phases. But if I then click on another browser window or Windows application and then go back to the SDLB UI, the filter is automatically reset.

@pgruetter  That's true, and this has to do with the relatively aggressive setting of the "React Query" library. Long story short, it probes the remote source for changes continuously as you are on the window. If it detect you were on another tab/application for even a short period, it re-triggers a fetch. Since I have not set the states to persist upon re-fetch, the whole page is reloaded and filters are reset. I suggest adding this to the backlog and defining the correct behavior we want.


> 1. In my opinion the duration should be the sum of all intervals displayed, e.g. if Prep/Init/Exec is displayed it should be durationPrep + durationInit + duration Exec. If we would just display tstmpExecEnd - tstampPrepStart the value would be unusable as well...

@zzeekk @pgruetter I will implement the time for an action as the addition of the duration of each phases 👍

**Review by pgruetter — APPROVED** [review]
Thanks a lot for fixing everything, now it looks great!

**Pull request merged**
